version: '3'

services: 
  db:
    image: mysql:5.7.37
    restart: always
    ports:
      - 3306:3306
    environment: 
      MYSQL_RANDOM_ROOT_PASSWORD: absolutely
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes: 
      - dbdata:/var/lib/mysql
    networks:
      - instrumentenplatform

  phpmyadmin:
    image: phpmyadmin:5.1.3-apache
    restart: always
    ports: 
      - 8081:80
    links:
      - db
    networks:
      - instrumentenplatform
      
  server:
    build:
      context: .
      dockerfile: Dockerfile
    user: node
    restart: always
    ports: 
      - 4000:4000
    working_dir: /home/node
    expose: 
      - 4000
    depends_on: 
      - db
    command: "npm run start"
    networks:
      - instrumentenplatform

volumes:
  dbdata:

networks:
  instrumentenplatform:
    external: true